apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: axion-pgdb-pvc
  namespace: axion-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  storageClassName: axion-pgdb-storageclass
  
